# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-15 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0003_auto_20190814_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.CharField(default='blank notes', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(default='blank description', max_length=255),
            preserve_default=False,
        ),
    ]
